### ISSUE TITLE
Loop Pipelining with distance > 1

### ISSUE THREAD

**Issue by giuseros** [google/iree-llvm-sandbox#112]
Hi all, 
I was wondering how hard would it be to add support for `distance >1` carried dependencies in the `LoopPipelining` pass. Basically I have a loop like:
```
for (..){
Load0
Compute0
Load1
Compute1
Load2
Compute2
Load3
Compute3
}
```

And I want to have:
```
Load0
Compute0
Load1
for(...){
Load2
Compute0
Load3
Compute1
Load0
Compute2
Load1
Compute3
```
This seems not possible in the current framework. Indeed, according to the following assert:
```
assert(def && "Only support loop carried dependencies of distance 1");
```
Is this something that you guys are working on?

Thanks,
Giuseppe

**Comment by nicolasvasilache** [comment]
@ThomasRaoux for this

**Comment by giuseros** [comment]
cc @ThomasRaoux , since I think you worked on this

**Comment by ThomasRaoux** [comment]
@giuseros, the distance of 1 limitation is on the original loop, the code can already handle generating pipelined loops with distances greater than one. For instance this case generates a distance of 4:
https://github.com/llvm/llvm-project/blob/423f19680a4fc60c106cef102730939c3c7ab7ac/mlir/test/Dialect/SCF/loop-pipelining.mlir#L92

You example does't seem to have a distance > 1 in the original loop?

I don't think it is extra hard to support distance > 1 but it requires extra logic I haven't added yet. If you have an example you are trying to make work it would be great if you could share it and I can help looking at what is missing to make it work.

**Comment by giuseros** [comment]
Hi @ThomasRaoux , 
THanks for the reply. Ok, I see, I thought that the distance was referring to the pipelined loop, and this assumption stemmed ly because when I try to pipeline in the way I showed to you, I get an assert about instruction destroyed but still used. 

I will try to dig a bit more into this and ask more questions if I get stuck !

**Comment by ThomasRaoux** [comment]
Sounds good, feel free to create a bug or send a repro on this thread if you need help debugging this.

**Comment by giuseros** [comment]
Thank you so much! Actually, I was doing something very stupid, but now I got it working. Basically I didn't really want the for-loop I showed the first message, but what I really wanted was this one:
```
Load0
Load1
for(...){
Load2
Compute0
Load3
Compute1
Load0
Compute2
Load1
Compute3
}
Compute0
Compute1
```
The first two loads are in stages 0 and 1 and the remaining things in stage 2 !

Et voila', now it works :)

Thanks again,
Giuseppe

**Comment by ThomasRaoux** [comment]
Awesome :)
