### ISSUE TITLE
Instructions out of date?

### ISSUE THREAD

**Issue by srcarroll** [google/iree-llvm-sandbox#2]
I'm trying to build iree-llvm-sandbox and run some of the python scripts.  I'm using commit 70804f2a2f7b87227a873cd6d8852ad295068e79 for llvm-project.  There are a few problems

1) In Python prerequisites section:
    ${LLVM_SOURCE_DIR}/mlir/lib/Bindings/Python/requirements.txt
    doesn't exist.  It exists in an older version of llvm-project though. I don't understand
    because the last update I have for iree-llvm-sandbox is June 3 and the last update I 
    have for llvm-project is June 1.  Even trying the older version gives build errors.  The 
    only requirements files I see are in clang/utils/analyzer/requirements.txt and
    mlir/python/requirements.txt.  I tried the latter since it seems to be the more relevant 
    one.

2) Everything builds fine, but I'm trying to run the python sanity check
    python \
    ${IREE_LLVM_SANDBOX_SOURCE_DIR}/runners/test/python/linalg_matmul.py
    and get
        from mlir.ir import *
ModuleNotFoundError: No module named 'mlir'
 
3) I can manage to find where this is located and at it to python path. However, there are still more modules it can't find. At that point I gave up trying to track down python files.

What's the easiest way to get this working? Thanks

**Comment by nicolasvasilache** [comment]
Sorry for the long delay .. I haven't been monitoring the issues.
The instructions should be up-to-date for some time now but you have also probably moved on, sorry again for the unresponsiveness.
