### ISSUE TITLE
Segfault in some matmul cases

### ISSUE THREAD

**Issue by hanhanW** [google/iree-llvm-sandbox#299]
I was running matmul benchmarks on some shapes and found that it would crash for some cases. It looks like there are bugs after bumping LLVM (commit https://github.com/google/iree-llvm-sandbox/commit/7c27887b9b543ebbc5f19b69eb3a6f9324ff227d)

Examples:

Run SingleTiling3DPeel with spec `km,kn->mn` with problem size `{'m': 512, 'n': 1024, 'k': 1024}`.

Run SingleTiling3DPeel with spec `mk,kn->mn` with problem size `{'m': 512, 'n': 1024, 'k': 1024}`.

Run DoubleTile2DPadAndHoist with spec `mk,kn->mn` with problem size `{'m': 128, 'n': 384, 'k': 1536}`.

**Comment by giuseros** [comment]
Hi @hanhanW , 
Yes, after rebasing I am having the same issues. I am trying to investigate a bit more, but if you have any hint, please let me know. 

Thanks,
Giuseppe

**Comment by giuseros** [comment]
Actually, what I found is that some `memref.alloca()` instructions creep in during `LowerVector` transformation. If you set `ulimit -s unlimited` it should be fine, but I am guessing if this was intentional.

**Comment by giuseros** [comment]
And the winner is: https://reviews.llvm.org/D119743 :) 

By adding `AutomaticAllocationScope` to `scf::ForOp` makes [this](https://github.com/llvm/llvm-project/blob/f37d21ed20fb069b8706b9a4afbac7d373ecb18b/mlir/lib/Dialect/Vector/Transforms/VectorTransferSplitRewritePatterns.cpp#L442) always returning the `scf:::ForOp` instead of the `FuncOp`. 

This means that there are a lot of `alloca` that now happens inside the loops, that cannot be hosted out, and that make the stack explode.

**Comment by ftynse** [comment]
I suppose we can extend the function that finds the appropriate alloca insertion point to something like "find the farthest allocation scope that is not isolated from above".

We also discussed with the author of [D119743](https://reviews.llvm.org/D119743) the idea of having an "alloca hoisting" pass that would hoist allocas from nested scopes. They originally wanted it to be a canonicalization pattern, but this may have unintended consequences as the allocation lifetime is being extended and fake dependencies being introduced across different loop iterations. If you are willing to contribute such a transformation upstream, it would be very helpful.

**Comment by ftynse** [comment]
This trivial fix lets the search step over loops. @hanhanW, please check if this helps with your issue.

```
--- a/mlir/lib/Dialect/Vector/Transforms/VectorTransferSplitRewritePatterns.cpp
+++ b/mlir/lib/Dialect/Vector/Transforms/VectorTransferSplitRewritePatterns.cpp
@@ -439,8 +439,14 @@ static void createFullPartialVectorTrans
 
 // TODO: Parallelism and threadlocal considerations with a ParallelScope trait.
 static Operation *getAutomaticAllocationScope(Operation *op) {
-  Operation *scope =
-      op->getParentWithTrait<OpTrait::AutomaticAllocationScope>();
+  Operation *scope = nullptr;
+  for (Operation *parent = op->getParentOp(); parent != nullptr;
+       parent = parent->getParentOp()) {
+    if (parent->hasTrait<OpTrait::AutomaticAllocationScope>())
+      scope = parent;
+    if (!isa<scf::ForOp>(parent))
+      break;
+  }
   assert(scope && "Expected op to be inside automatic allocation scope");
   return scope;
 }
```

**Comment by ftynse** [comment]
Fix applied in https://github.com/llvm/llvm-project/commit/4c807f2f579f4e5412c49c341230e309f2f79c9b

**Comment by hanhanW** [comment]
Thanks for the fix!
