### ISSUE TITLE
Error in PDL after Interpreter refactoring

### ISSUE THREAD

**Issue by giuseros** [google/iree-llvm-sandbox#300]
HI @ftynse , 
After your refactoring of the `LinalgInterpreter` (https://github.com/google/iree-llvm-sandbox/pull/289) , I am not able to pattern-match any computation that involves tiling+padding. This is what I am doing:

```
tiled = transform.TileOp(matched, sizes =...)
padded = transform.TileOp(padded , pad=True...)
transform.VectorizeOp(padded , vectorize_padding=False)
```
And this is the error I am getting:
```
loc("-":18:10): error: operation tracked by two handles
error: failed to apply
```

The code has become quite convoluted, so I am struggling to understand what is going on. Do you have any hints? Can you reproduce that on your side?

Thanks,
Giuseppe

**Comment by giuseros** [comment]
It looks like this check is too strict:
```
  const SmallVector<Operation *> &currentOperationList =
      operations.lookup(value);
  llvm::SmallPtrSet<Operation *, 4> currentOperationSet(
      currentOperationList.begin(), currentOperationList.end());
  for (const auto &kvp : operations) {
    if (kvp.getFirst() == value)
      continue;
    for (Operation *trackedOp : kvp.getSecond()) {
      if (currentOperationSet.contains(trackedOp)) {
        InFlightDiagnostic diag = trackedOp->emitError()
                                  << "operation tracked by two handles";
        diag.attachNote(value.getLoc()) << "handle";
        diag.attachNote(kvp.getFirst().getLoc()) << "handle";
        return diag;
      }
    }
  }
```
Because if I remove it, it simply works fine. Could you explain what exactly the check is doing? Is it checking that we don't run multiple transformations multiple times?

**Comment by ftynse** [comment]
```
padded = transform.TileOp(padded , pad=True...)
```

This line looks suspicious: it somehow uses the same value it assigns.

The general intuition here is that we don't want to have two handles point to the same operation because handles are used in transformations that are likely to invalidate the operation: the second handle then have a dangling pointer or, worse, point to a different operation that just happens to reuse pointer address. Look at the transform IR that this code constructs, something like

```
%0 = match
%1 = tile %0 {...}
%2 = tile %1 {...}
vectorize %2
```

should work, something like

```
%0 = match
%1 = tile %0 {...}
%2 = tile %0 {...}
vectorize %2
```

should not (the first tiling will actually recreate the main op so %0 points nowhere, which is why the check exists in the first place).

**Comment by giuseros** [comment]
Hi @ftynse ,
Thanks for the answer. 

Sorry, the `pad = tile(pad) `  was a copy/paste typo. What I am doing is exactly `vectorize(tile(tile))` but somehow that check is failing

I am also using generic ops and full dynamic operations, and that might make things a bit more confused for the checker.

**Comment by giuseros** [comment]
Hi @ftynse ,
FYI, the problem was in the way you add/remove transformation payloads in `applyTransform`. 

What you do is to `apply transform` -> `add new payloads`  -> `remove old payloads`. But in this way old payloads will be verified as well during the `add new payloads` phase (and will generate errors). 

If you switch the order in `apply transform` -> `remove old payloads` ->  `add new payloads`  everything works fine
