### ISSUE TITLE
Why the sandbox depends on Clang and its tools?

### ISSUE THREAD

**Issue by chelini** [google/iree-llvm-sandbox#350]
Dear All,
I wonder why the sandbox builds also Clang and Clang tools. Why not MLIR only?
See:
https://github.com/google/iree-llvm-sandbox/blob/a931c4b3da986fe2c6515a43dd578baf185c628e/configure.py#L111

**Comment by gysit** [comment]
I think they are not built by default. The script actually builds only a subset of the targets. 

cf here: 
https://github.com/google/iree-llvm-sandbox/blob/a931c4b3da986fe2c6515a43dd578baf185c628e/configure.py#L244

It seems like alps used clang? 
https://github.com/google/iree-llvm-sandbox/blob/a931c4b3da986fe2c6515a43dd578baf185c628e/configure.py#L250

You are at the source to figure that out :).

**Comment by nicolasvasilache** [comment]
I have been building more things than strictly necessary so that the tools/llvm_mca.py script is functional.
If it poses a problem, feel free to add a new flag and turn off by default.

**Comment by chelini** [comment]
Thanks, both.
