### ISSUE TITLE
Possible Huawei cooperation

### ISSUE THREAD

**Issue by giuseros** [google/iree-llvm-sandbox#5]
Hi all, 
@stellaraccident, @nicolasvasilache  and I are trying to bootstrap an open cooperation between Google and Huawei efforts to generate highly efficient linear algebra (and sparse) operations directly from MLIR (see this [PR](https://github.com/google/iree-llvm-sandbox/pull/4), thanks @stellaraccident ). 

# Introduction 
Some of you might have noticed that we have been recently posting on the discourse forum about the main bottlenecks we met to generate an optimal GEMM routine (which is our starting point) targeting Arm architectures:
- https://llvm.discourse.group/t/micro-kernel-analysis-in-mlir
- https://llvm.discourse.group/t/latency-hiding-pipeline-representation-in-mlir
- https://llvm.discourse.group/t/outer-product-spillingb
- https://llvm.discourse.group/t/mlir-linalg-bad-perfomance

To fulfill those investigations we created an internal repository which is in spirit very similar to this sandbox (a core c++ compiler+passes, a python interface, and a tool for searching the optimal transformations)

Now that we have a (vaguely) clearer picture of what transformations we might want to implement, we would like to join efforts and use this repository  to keep experimenting with those transformations (instead of creating our own and possibly duplicating everything). 

# Why I am writing this?
I want to use this thread to organize an online meeting where we can talk and openly discuss how to proceed further. I think the main topics to discuss should be (feel free to add more):
* What are our goals and what are our future plans
* What the development process should look like (PRs, reviews, etc..)
* How to proceed quickly (i.e., making the dev process as light as possible) but maintaining a stable core (e.g., , to avoid sudden changes in interfaces, functionalities, etc..)
* How to share ideas, updates, and interesting work

I was thinking that we could have short presentations about goals and plans (the what), and then we can have a discussion about cooperation (the how)

# Conclusion
I created a doodle for the meeting: 
https://doodle.com/poll/ggzcewwqxhbuzses

Anyone that wants to participate, feel free to fill it in. Once we decide for the day, we can agree on a common time frame (also depending by the time-zone of the participants). 

Let me copy some people from Huawei that are working on this: @Joey-Ye  @Japhonix (our project supervisors) @stevenvar (working on hoisting and packing) @chelini (our MLIR expert)

Let's do this! 🚀 

Thanks,
Giuseppe

**Comment by nicolasvasilache** [comment]
Thanks for starting this @giuseros 

Note that this is Thanksgiving week for our US-based friends, I expect them to be unavailable Wed-Sun, maybe remove those days from the options?

Since we are talking about synchronizing with CA/SEA could you please break down into 3 time regions?

- 10am-4pm GMT: W coast not expected to participate.
- 4pm-6pm GMT: maybe we get lucky and get most participants in this slot.
- 8pm-11pm GMT: I can at those times on Wednesdays and Thursdays.

Thanks!

**Comment by giuseros** [comment]
Hi @nicolasvasilache , 
Thanks for the suggestion,  I just updated the [doodle](https://doodle.com/poll/ggzcewwqxhbuzses)!

Cheers,
Giuseppe

**Comment by MaheshRavishankar** [comment]
The 4PM - 6PM slot seems most feasible. That is 8 AM - 10 AM on the West coast. 9 AM PDT (or 5PM GMT) seems ideal.

**Comment by giuseros** [comment]
Hi all, I would say that the Monday 29th at 5PM seems the best candidate. Is this ok for everybody?

**Comment by nicolasvasilache** [comment]
Yes, 29th at 9AM PST / 5PM GMT / 6PM CEST sounds like the most plausible option, I'll advertise internally.

**Comment by nicolasvasilache** [comment]
I added a public meeting option on our side: meet.google.com/ipv-qdyx-yxg

**Comment by nicolasvasilache** [comment]
Meeting was fruitful, closing the issue.
