### ISSUE TITLE
python fusion test does not run

### ISSUE THREAD

**Issue by ftynse** [google/iree-llvm-sandbox#58]
The `python/fusion/test.py` has the main function, but is never called, so running it with `python -m` does nothing and predictably succeeds.

**Comment by gysit** [comment]
After https://github.com/google/iree-llvm-sandbox/pull/55 the main function will be called. However, the test does only compile and print the IR for now. Adding verification and performance measurements is still a TODO.

**Comment by MaheshRavishankar** [comment]
If you see the TODO here (https://github.com/google/iree-llvm-sandbox/blob/fc5dcf3d511bfdaa1033475541292191aaeaa0ce/python/fusion/test.py#L52) it should work when run manually (comments use bazel but same should work with CMake). Issue when I tried this first time around is that I didnt have a driver for the lit tests from bazel. I have no idea how any of the python stuff is setup, but would be great to enable this. I know core already has this.

**Comment by ftynse** [comment]
Well it does "run" and does nothing because `main` is never called, bazel or not. The only check performed by FileCheck is the absence of "FAILURE" printed, which is the case when the code does nothing and prints nothing.
